name: mk_splash_screen
description: A new Flutter package which helps developers in creating splashscreen of their app.
version: 0.0.1
author: MgKaung <developer.mgkaung>
homepage: https://github.com/dev-mgkaung/Mk-SplashScreen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

